#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : efibootmgr
Version  : 16
Release  : 8
URL      : https://github.com/rhboot/efibootmgr/releases/download/16/efibootmgr-16.tar.bz2
Source0  : https://github.com/rhboot/efibootmgr/releases/download/16/efibootmgr-16.tar.bz2
Summary  : EFI Boot Manager
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: efibootmgr-bin
Requires: efibootmgr-doc
BuildRequires : pkgconfig(efiboot)
BuildRequires : pkgconfig(popt)

%description
This is efibootmgr, a Linux user-space application to modify the Intel
Extensible Firmware Interface (EFI) Boot Manager.  This application
can create and destroy boot entries, change the boot order, change
the next running boot option, and more.

%package bin
Summary: bin components for the efibootmgr package.
Group: Binaries

%description bin
bin components for the efibootmgr package.


%package doc
Summary: doc components for the efibootmgr package.
Group: Documentation

%description doc
doc components for the efibootmgr package.


%prep
%setup -q -n efibootmgr-16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525540720
make  %{?_smp_mflags} EFIDIR=org.clearlinux

%install
export SOURCE_DATE_EPOCH=1525540720
rm -rf %{buildroot}
%make_install EFIDIR=org.clearlinux
## make_install_append content
install -D -m 00755 src/efibootmgr %{buildroot}/usr/bin/efibootmgr
install -D -m 00644 src/efibootmgr.8 %{buildroot}/usr/share/man/man8/efibootmgr.8
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/efibootdump
/usr/bin/efibootmgr

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
