#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : efibootmgr
Version  : 0.12
Release  : 4
URL      : https://github.com/vathpela/efibootmgr-devel/archive/efibootmgr-0.12.tar.gz
Source0  : https://github.com/vathpela/efibootmgr-devel/archive/efibootmgr-0.12.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: efibootmgr-bin
Requires: efibootmgr-doc
BuildRequires : pkgconfig(efiboot)

%description
This is efibootmgr, a Linux user-space application to modify the Intel
Extensible Firmware Interface (EFI) Boot Manager.  This application
can create and destroy boot entries, change the boot order, change
the next running boot option, and more.

%package bin
Summary: bin components for the efibootmgr package.
Group: Binaries

%description bin
bin components for the efibootmgr package.


%package doc
Summary: doc components for the efibootmgr package.
Group: Documentation

%description doc
doc components for the efibootmgr package.


%prep
%setup -q -n efibootmgr-devel-efibootmgr-0.12

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install
## make_install_append content
install -D -m 00755 src/efibootmgr/efibootmgr %{buildroot}/usr/bin/efibootmgr
install -D -m 00644 src/man/man8/efibootmgr.8 %{buildroot}/usr/share/man/man8/efibootmgr.8
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/efibootmgr

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
