#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : efibootmgr
Version  : 18
Release  : 12
URL      : https://github.com/rhboot/efibootmgr/releases/download/18/efibootmgr-18.tar.bz2
Source0  : https://github.com/rhboot/efibootmgr/releases/download/18/efibootmgr-18.tar.bz2
Summary  : EFI Boot Manager
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: efibootmgr-bin = %{version}-%{release}
Requires: efibootmgr-license = %{version}-%{release}
Requires: efibootmgr-man = %{version}-%{release}
BuildRequires : pkgconfig(efiboot)
BuildRequires : pkgconfig(popt)

%description
This is efibootmgr, a Linux user-space application to modify the Intel
Extensible Firmware Interface (EFI) Boot Manager.  This application
can create and destroy boot entries, change the boot order, change
the next running boot option, and more.

%package bin
Summary: bin components for the efibootmgr package.
Group: Binaries
Requires: efibootmgr-license = %{version}-%{release}

%description bin
bin components for the efibootmgr package.


%package license
Summary: license components for the efibootmgr package.
Group: Default

%description license
license components for the efibootmgr package.


%package man
Summary: man components for the efibootmgr package.
Group: Default

%description man
man components for the efibootmgr package.


%prep
%setup -q -n efibootmgr-18
cd %{_builddir}/efibootmgr-18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672171145
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}  EFIDIR=org.clearlinux


%install
export SOURCE_DATE_EPOCH=1672171145
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/efibootmgr
cp %{_builddir}/efibootmgr-%{version}/COPYING %{buildroot}/usr/share/package-licenses/efibootmgr/74a8a6531a42e124df07ab5599aad63870fa0bd4
cp %{_builddir}/efibootmgr-%{version}/NOTICE %{buildroot}/usr/share/package-licenses/efibootmgr/74a8a6531a42e124df07ab5599aad63870fa0bd4
%make_install EFIDIR=org.clearlinux
## install_append content
install -D -m 00755 src/efibootmgr %{buildroot}/usr/bin/efibootmgr
install -D -m 00644 src/efibootmgr.8 %{buildroot}/usr/share/man/man8/efibootmgr.8
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/efibootdump
/usr/bin/efibootmgr

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/efibootmgr/74a8a6531a42e124df07ab5599aad63870fa0bd4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/efibootdump.8
/usr/share/man/man8/efibootmgr.8
